version: '3.8'

services:
  linkmeet-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: linkmeet-backend
    ports:
      - "5001:5000"  # App: localhost:5001 -> container:5000
      - "5002:5555"  # Prisma Studio: localhost:5002 -> container:5555
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - linkmeet-network
    depends_on: []
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  linkmeet-network:
    driver: bridge

volumes:
  logs:
    driver: local